---
- name: Installing your favorite packages
  become: true
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items: "{{ apt_packages }}"

- name: Check SSH key existence
  register: ssh_key_file
  stat: path="{{ lookup('env', 'HOME') }}/.ssh/id_rsa"

- name: Generate SSH key
  user:
    name: "{{ lookup('env', 'USER') }}"
    generate_ssh_key: yes
  when: ssh_key_file.stat.exists == False

- name: Save zsh path
  register: which_zsh
  shell: "which zsh"

- name: Set zsh as user's shell
  become: true
  user:
    name: "{{ lookup('env', 'USER') }}"
    shell: "{{ which_zsh.stdout }}"

- name: Install oh-my-zsh
  git:
    dest: ~/.oh-my-zsh
    repo: git://github.com/robbyrussell/oh-my-zsh.git
    depth: 1

- name: Symlink dot files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.{{ item }}"
    state: link
    force: yes
  with_items: "{{ dot_files }}"

- name: Ensure strange dot files destination folders exist
  file:
    path: "{{ item.dest }}"
    state: directory
    force: yes
  with_items: "{{ strange_dot_files }}"

- name: Symlink strange dot files
  file:
    src: "{{ role_path }}/files/{{ item.name }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ strange_dot_files }}"

- name: Install n - node version manager
  become: true
  npm:
    name: n
    global: yes
    state: latest

- name: Install latest node using n
  become: true
  shell: "n latest"

- name: Install stable node using n
  become: true
  shell: "n stable"
