---
- name: Making a funny text file on the desktop
  copy:
    dest: "/home/amir/Desktop/jesus message.txt"
    content: "Jesus engulfs you"

- name: Installing your favorite packages
  become: true
  apt:
    update_cache: yes
    name: "{{ item }}"
    state: latest
  with_items: "{{ apt_packages }}"

- name: Install n - node version manager
  become: true
  npm:
    name: n
    global: yes
    state: latest

- name: Install latest node using n
  become: true
  shell: "n latest"

- name: Install stable node using n
  become: true
  shell: "n stable"
