---
- name: Install n - node version manager
  become: true
  npm:
    name: n
    global: yes
    state: latest

- name: Install latest node using n
  become: true
  shell: "n latest"

- name: Install stable node using n
  become: true
  shell: "n stable"
