# more shell extensions/utils

---

- name: Add ~/bin to PATH
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/bin:S$PATH"'


- name: Install fzf from git (fuzzy search)
  git:
    dest: ~/.fzf
    repo: https://github.com/junegunn/fzf.git
    depth: 1

- name: Run fzf install script
  shell: "{{ ansible_env.HOME }}/.fzf/install"

