---
- name: Installing your favorite packages, Debian family
  become: true
  apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    name: "{{ apt_packages }}"
    state: latest
  when: ansible_os_family == "Debian"

- name: Installing your favorite packages, Arch family
  become: true
  pacman:
    update_cache: yes
    name: "{{ pacman_packages }}"
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Installing your favorite packages, SUSE family
  become: true
  zypper:
    update_cache: yes
    name: "{{ suse_packages }}"
    state: latest
  when: ansible_os_family == "Suse"

- include_tasks: dotfiles.yml
- include_tasks: zsh.yml
- include_tasks: shell.yml
- include_tasks: python.yml
- include_tasks: node.yml
