---
- name: Install n - node version manager
  become: true
  npm:
    name: n
    global: yes
    state: latest

- name: Install latest node using n
  become: true
  shell: "/usr/local/bin/n latest"

- name: Install stable node using n
  become: true
  shell: "/usr/local/bin/n stable"

- name: Global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: latest
  with_items: "{{ global_npm_packages }}"
