---
- name: "Clone the js/ts lang server repository"
  git:
    depth: 1
    repo: https://github.com/sourcegraph/javascript-typescript-langserver
    dest: "{{ js_ts_langserver_path }}"

- name: "npm install for the js/ts lang server"
  npm:
    path: "{{ js_ts_langserver_path }}"


- name: "Build js/ts langserver"
  shell: npm run build
  args:
    chdir: "{{ js_ts_langserver_path }}"

