---
- name: Ensure user personal bin folder
  file:
    path: "{{ personal_bin_folder }}"
    state: directory
    force: yes

- name: Download nightly nvim.appimage
  get_url:
    url: "{{ nvim_appimage_url }}"
    dest: "{{ personal_bin_folder }}/nvim"
    mode: u+rwx

- name: Installed required packages, Debian family
  become: true
  apt:
    name: xclip
    state: latest
  when: ansible_os_family == "Debian"

- name: Installed required packages, Arch family
  become: true
  pacman:
    name: xclip
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Ensure virtualenv in Python 2
  pip:
    virtualenv_python: python2.7
    name: "virtualenv"

- name: Ensure virtualenv in Python 3
  pip:
    virtualenv_python: python3
    name: "virtualenv"

- name: Install python2 neovim on a virtualenv
  pip:
    virtualenv_python: python2.7
    virtualenv: "{{ python2_host_venv_path }}"
    name: "neovim"
    state: latest

- name: Install python3 neovim on a virtualenv
  pip:
    virtualenv_python: python3
    virtualenv: "{{ python3_host_venv_path }}"
    name: "neovim"
    state: latest

- name: Ensure neovim config folder
  file:
    path: "{{ neovim_config_folder }}"
    state: directory
    force: yes

- name: Symlink configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "{{ neovim_config_folder }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - "init.vim"
    - "autoload"
    - "amir"

- name: Run nvim installation things
  shell: "{{ personal_bin_folder }}/nvim +'PlugInstall --sync' +UpdateRemotePlugins +qa"


