---
- name: Ensure user ~/bin folder
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    force: yes

- name: Download nightly nvim.appimage
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage"
    dest: "{{ ansible_env.HOME }}/bin/nvim"
    mode: u+rwx

- name: Install python2 neovim on a virtualenv
  pip:
    virtualenv_python: python2.7
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/neovim-py2"
    name: "neovim"
    state: latest

- name: Install python3 neovim on a virtualenv
  pip:
    virtualenv_python: python3
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/neovim-py3"
    name: "neovim"
    state: latest

- name: Symlink configuration files
  file:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/.config/nvim/{{ item }}"
    state: link
    force: yes
  with_items:
    - "init.vim"
    - "plug.vim"
    - "amir"

- name: Run nvim installation things
  shell: "nvim +'PlugInstall --sync' +UpdateRemotePlugins +qa"


