---
- name: Ensure we got build tools (CMake)
  become: true
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - cmake
    - build-essential

- name: Clone Neovim's repository
  git:
    depth=1
    dest="{{ local_repo }}"
    repo="{{ remote_repo }}"
    accept_hostkey=yes

- name: Build Neovim
  make:
    chdir: "{{ local_repo }}"
    file: "{{ local_repo }}/Makefile"
