---
- name: Ensure git, Debian family
  become: true
  apt:
    install_recommends: no
    update_cache: yes
    name: "git"
    state: latest
  when: ansible_os_family == "Debian"

- name: Ensure git, Arch family
  become: true
  pacman:
    update_cache: yes
    name: "git"
    state: latest
  when: ansible_os_family == "Archlinux"

- name: Check SSH key existence
  register: ssh_key_file
  stat: path="{{ ansible_env.HOME }}/.ssh/id_rsa"

- name: Generate SSH key
  become: true
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
  when: ssh_key_file.stat.exists == False

- name: Scan GitHub SSH host
  shell: "ssh-keyscan github.com > ~/.ssh/known_hosts"

- name: Check if amirize repository already exists at standard location
  stat:
    path: "~/.amirize-this-machine"
  register: amirize_repo

- name: Clone this amirize repository locally
  git:
    dest: "~/.amirize-this-machine"
    repo: "git@github.com:amireldor/amirize-this-machine.git"
  when: not amirize_repo.stat.exists


