---
# TODO: extract common packages to `common_packages`, concatenate in tasks/main.yml
apt_packages:
  - git
  - tig
  - build-essential
  - zsh
  - tree
  - npm
  - gnome-tweak-tool
  - trash-cli
  - meld
  - python-virtualenv
  - thefuck
  - tmux
  - curl
  - silversearcher-ag
  - git-flow
  - direnv
  - i3
  - i3status
  - feh
  - rofi
  - redshift-gtk
  - htop

pacman_packages:
  - git
  - tig
  - zsh
  - tree
  - npm
  - trash-cli
  - meld
  - python-virtualenv
  - thefuck
  - tmux
  - curl
  #- silversearcher-ag
  #- git-flow
  #- direnv
  - i3-gaps
  - feh
  - rofi
  - htop

dot_files:
  - zshrc
  - bash_aliases
  - npmrc
  - tmux.conf
  - bash_profile
  - gitconfig
  - gitignore_global

custom_path_dot_files:
  - name: astro.zsh-theme
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/themes/astro.zsh-theme"
  - name: i3.config
    dest: "{{ ansible_env.HOME }}/.config/i3/config"

global_npm_packages:
  - yarn
  - flow-bin
