---
apt_packages:
  - git
  - tig
  - build-essential
  - zsh
  - tree
  - npm
  - gnome-tweak-tool
  - trash-cli
  - meld
  - python-virtualenv
  - thefuck
  - tmux
  - curl
  - silversearcher-ag
  - git-flow
  - direnv
  - i3
  - feh
  - rofi

dot_files:
  - zshrc
  - bash_aliases
  - npmrc
  - tmux.conf
  - bash_profile
  - gitconfig

custom_path_dot_files:
  - name: astro.zsh-theme
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/themes/astro.zsh-theme"
  - name: i3.config
    dest: "{{ ansible_env.HOME }}/.config/i3/config"

global_npm_packages:
  - yarn

