---
apt_packages:
  - git
  - tig
  - build-essential
  - zsh
  - tree
  - npm
  - gnome-tweak-tool
  - trash-cli
  - meld
  - python-virtualenv
  - thefuck
  - tmux
  - curl
  - silversearcher-ag

dot_files:
  - zshrc
  - bash_aliases
  - npmrc
  - tmux.conf
  - bash_profile
  - gitconfig

custom_path_dot_files:
  - name: astro.zsh-theme
    dest: "$HOME/.oh-my-zsh/themes/astro.zsh-theme"

global_npm_packages:
  - yarn

